### ISSUE TITLE
word2vec.txt 编码

### ISSUE THREAD

**Issue by ZeR0ll** [vortexJCH/-LSTM-#1]
看了一下word2vec.txt的编码是latin,我在linux下打开直接是乱码的.建议用utf-8

**Comment by xixiU** [comment]
iconv -f GBK -t UTF-8 FILENAME  

了解一下

**Comment by JingGao-0423** [comment]
词向量连接在哪儿呢？

**Comment by wenxuan0313** [comment]
word2vec.model没有呢
